# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cpp_var <- function(x, na_rm = FALSE) {
    .Call(`_LS1MATH4753WS26_cpp_var`, x, na_rm)
}

